[project]
name = "stock_selection"
version = "0.1.0"
description = "stock_selection using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.9.3"
]

[project.scripts]
stock_selection = "stock_selection.main:run"
run_crew = "stock_selection.main:run"
train = "stock_selection.main:train"
replay = "stock_selection.main:replay"
test = "stock_selection.main:test"
run_with_trigger = "stock_selection.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
